---
version: '3.8'


volumes:
    backend-data:
    db-data:

services:

    backend:
        build:
            context: .
        command: bash -c "cd backend && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        restart: unless-stopped
        depends_on:
            - db
        env_file:
            - .env
        environment:
            - POSTGRES_HOST=db
        ports:
            - 8000:8000
        volumes:
            - backend-data:/data
            - .:/code

    db:
        image: postgres:13-alpine
        restart: unless-stopped
        env_file:
            - .env
        volumes:
            - db-data:/var/lib/postgresql/data
